(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by CoffeeScript 1.12.6
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = (function(superClass) {
    extend(exports, superClass);

    function exports(text, x, y) {
      var textLayer;
      textLayer = new TextLayer({
        x: 0,
        y: 0,
        text: text,
        fontFamily: 'Arial',
        fontSize: 12,
        color: '#000000',
        padding: 8
      });
      exports.__super__.constructor.call(this, {
        x: x,
        y: y,
        width: textLayer.width,
        height: textLayer.height,
        backgroundColor: '#eeeeee',
        borderRadius: 8,
        borderColor: '#000000',
        borderWidth: 1
      });
      this.addChild(textLayer);
      this.states.normal = {
        backgroundColor: '#eeeeee'
      };
      this.states.pressed = {
        backgroundColor: '#cccccc'
      };
      this.on(Events.Click, (function(_this) {
        return function(event, layer) {
          var downAnim, upAnim;
          downAnim = new Animation(_this, {
            backgroundColor: '#cccccc',
            options: {
              time: 0.25
            }
          });
          upAnim = downAnim.reverse();
          downAnim.on(Events.AnimationEnd, upAnim.start);
          return downAnim.start();
        };
      })(this));
    }

    return exports;

  })(Layer);

}).call(this);

},{}],2:[function(require,module,exports){
// Generated by CoffeeScript 1.12.6
(function() {
  var HButton, __, button;

  __ = require('./utils');

  HButton = require('./button');

  button = new HButton('Create', 10, 5);

}).call(this);

},{"./button":1,"./utils":3}],3:[function(require,module,exports){
// Generated by CoffeeScript 1.12.6
(function() {
  module.exports = {
    centerize: function(overLayer, underLayer) {
      var paddingX, paddingY;
      paddingX = (underLayer.width - overLayer.width) / 2;
      paddingY = (underLayer.height - overLayer.height) / 2;
      overLayer.x = underLayer.x + paddingX;
      return overLayer.y = underLayer.y + paddingY;
    },
    centerizedPoint: function(overLayer, underLayer) {
      var paddingX, paddingY;
      paddingX = (underLayer.width - overLayer.width) / 2;
      paddingY = (underLayer.height - overLayer.height) / 2;
      return {
        x: underLayer.x + paddingX,
        y: underLayer.y + paddingY
      };
    },
    middleY: function(layer) {
      return layer.y + layer.height / 2;
    },
    middleX: function(layer) {
      return layer.x + layer.width / 2;
    },
    alignX: function(layer, fixedLayer) {
      return layer.x = _middleX(fixedLayer.x) - layer.width / 2;
    },
    above: function(layer, fixedLayer, margin) {
      return layer.y = fixedLayer.y - (_.isNil(margin) ? layer.height : margin);
    }
  };

}).call(this);

},{}]},{},[2]);
