// Generated by CoffeeScript 1.12.6
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = (function(superClass) {
    extend(exports, superClass);

    function exports(text, x, y) {
      var textLayer;
      textLayer = new TextLayer({
        x: 0,
        y: 0,
        text: text,
        fontFamily: 'Arial',
        fontSize: 12,
        color: '#000000',
        padding: 8
      });
      exports.__super__.constructor.call(this, {
        x: x,
        y: y,
        width: textLayer.width,
        height: textLayer.height,
        backgroundColor: '#eeeeee',
        borderRadius: 8,
        borderColor: '#000000',
        borderWidth: 1
      });
      this.addChild(textLayer);
      this.states.normal = {
        backgroundColor: '#eeeeee'
      };
      this.states.pressed = {
        backgroundColor: '#cccccc'
      };
      this.on(Events.Click, (function(_this) {
        return function(event, layer) {
          var downAnim, upAnim;
          downAnim = new Animation(_this, {
            backgroundColor: '#cccccc',
            options: {
              time: 0.25
            }
          });
          upAnim = downAnim.reverse();
          downAnim.on(Events.AnimationEnd, upAnim.start);
          return downAnim.start();
        };
      })(this));
    }

    return exports;

  })(Layer);

}).call(this);
