// Generated by CoffeeScript 1.12.6
(function() {
  var ClusterView,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  exports.ClusterView = ClusterView;

  ClusterView = (function(superClass) {
    extend(ClusterView, superClass);

    function ClusterView(cluster) {
      var height, max_x, max_y, min_x, min_y, width, x, y;
      this.cluster = cluster;
      min_x = _.head(_.sortBy(this.cluster.points, function(point) {
        return point[0];
      }))[0];
      max_x = _.head(_.reverse(_.sortBy(this.cluster.points, function(point) {
        return point[0];
      })))[0];
      min_y = _.head(_.sortBy(this.cluster.points, function(point) {
        return point[1];
      }))[1];
      max_y = _.head(_.reverse(_.sortBy(this.cluster.points, function(point) {
        return point[1];
      })))[1];
      height = max_y - min_y;
      width = max_x - min_x;
      x = this.cluster.centroid[0] - (width / 2);
      y = this.cluster.centroy[0] - (height / 2);
      ClusterView.__super__.constructor.call(this, {
        x: x,
        y: y,
        width: width,
        height: height,
        backgroundColor: "#EEDDDD"
      });
      this.sendToBack();
    }

    return ClusterView;

  })(Layer);

}).call(this);
