// Generated by CoffeeScript 1.12.6
(function() {
  var __,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __ = require('./utils');

  module.exports = (function(superClass) {
    extend(exports, superClass);

    function exports(displayName, pos) {
      var healthBarLayer, nameTextLayer;
      this.displayName = displayName;
      this.pos = pos;
      this.health = 100;
      this.energy = 100;
      this.hunger = 100;
      this.thirst = 100;
      this.sex = 100;
      this.pleasure = 100;
      exports.__super__.constructor.call(this, {
        name: 'creature_' + this.displayName.toLowerCase().split(' ').join('_'),
        width: 50,
        height: 50,
        backgroundColor: '#0099ff',
        borderRadius: 12
      });
      nameTextLayer = new TextLayer({
        text: this.displayName,
        fontSize: 15,
        fontFamily: 'Arial',
        textAlign: 'center',
        x: this.x,
        y: this.y,
        width: this.width,
        color: '#000000'
      });
      this.addChild(nameTextLayer);
      healthBarLayer = new Layer({
        x: this.x,
        y: this.y,
        width: this.width,
        height: 5,
        backgroundColor: '#00ff00',
        borderWidth: 1,
        borderColor: '#000000'
      });
      this.addChild(healthBarLayer);
      __.above(healthBarLayer, this, 10);
      __.above(nameTextLayer, healthBarLayer, 20);
    }

    return exports;

  })(Layer);

}).call(this);
