// Generated by CoffeeScript 1.12.6
(function() {
  var Position;

  module.exports = Position = (function() {
    function Position(i, j) {
      this.i = i;
      this.j = j;
    }

    Position.prototype.isEqual = function(pos) {
      return this.i === pos.i && this.j === pos.j;
    };

    Position.prototype.next = function(direction) {
      if (direction === "up") {
        return new Position(this.i, this.j - 1);
      } else if (direction === "down") {
        return new Position(this.i, this.j + 1);
      } else if (direction === "left") {
        return new Position(this.i - 1, this.j);
      } else if (direction === "right") {
        return new Position(this.i + 1, this.j);
      } else {
        return null;
      }
    };

    return Position;

  })();

}).call(this);
