// Generated by CoffeeScript 1.12.7
(function() {


}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29kZV9yZW5kZXIuanMiLCJzb3VyY2VSb290IjoiLi4iLCJzb3VyY2VzIjpbInNyY19jb2ZmZWUvY29kZV9yZW5kZXIuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7QUFBQSIsInNvdXJjZXNDb250ZW50IjpbIiJdfQ==
//# sourceURL=/Users/gvieira/code/hare/hare_framer/src_coffee/code_render.coffee