// Generated by CoffeeScript 1.12.7
(function() {


}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29kZV9tb3ZlLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJzcmNfY29mZmVlL2NvZGVfbW92ZS5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOztBQUFBIiwic291cmNlc0NvbnRlbnQiOlsiIl19
//# sourceURL=/Users/gvieira/code/hare/hare_framer/src_coffee/code_move.coffee