// Generated by CoffeeScript 1.12.7
(function() {
  var Edit, __;

  __ = require('./utils');

  module.exports = Edit = (function() {
    function Edit(program, position, operation) {
      this.program = program;
      this.position = position;
      this.operation = operation;
    }

    Edit.prototype.perform = function() {
      return {
        program: this.program,
        position: this.position
      };
    };

    return Edit;

  })();

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZWRpdC5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsic3JjX2NvZmZlZS9lZGl0LmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7QUFBQSxNQUFBOztFQUFBLEVBQUEsR0FBSyxPQUFBLENBQVEsU0FBUjs7RUFFTCxNQUFNLENBQUMsT0FBUCxHQUF1QjtJQUNSLGNBQUMsT0FBRCxFQUFXLFFBQVgsRUFBc0IsU0FBdEI7TUFBQyxJQUFDLENBQUEsVUFBRDtNQUFVLElBQUMsQ0FBQSxXQUFEO01BQVcsSUFBQyxDQUFBLFlBQUQ7SUFBdEI7O21CQUNiLE9BQUEsR0FBUyxTQUFBO2FBQ1A7UUFBQyxPQUFBLEVBQVMsSUFBQyxDQUFBLE9BQVg7UUFBb0IsUUFBQSxFQUFVLElBQUMsQ0FBQSxRQUEvQjs7SUFETzs7Ozs7QUFKWCIsInNvdXJjZXNDb250ZW50IjpbIl9fID0gcmVxdWlyZSAnLi91dGlscydcblxubW9kdWxlLmV4cG9ydHMgPSBjbGFzcyBFZGl0XG4gIGNvbnN0cnVjdG9yOiAoQHByb2dyYW0sIEBwb3NpdGlvbiwgQG9wZXJhdGlvbikgLT5cbiAgcGVyZm9ybTogKCkgLT5cbiAgICB7cHJvZ3JhbTogQHByb2dyYW0sIHBvc2l0aW9uOiBAcG9zaXRpb259XG4iXX0=
//# sourceURL=/Users/gvieira/code/hare/hare_framer/src_coffee/edit.coffee