// Generated by CoffeeScript 1.12.7
(function() {
  var Position;

  module.exports = Position = (function() {
    function Position(i, j) {
      this.i = i;
      this.j = j;
    }

    Position.prototype.isEqual = function(pos) {
      return this.i === pos.i && this.j === pos.j;
    };

    Position.prototype.next = function(direction) {
      if (direction === "up") {
        return new Position(this.i, this.j - 1);
      } else if (direction === "down") {
        return new Position(this.i, this.j + 1);
      } else if (direction === "left") {
        return new Position(this.i - 1, this.j);
      } else if (direction === "right") {
        return new Position(this.i + 1, this.j);
      } else {
        return null;
      }
    };

    return Position;

  })();

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicG9zaXRpb24uanMiLCJzb3VyY2VSb290IjoiLi4iLCJzb3VyY2VzIjpbInNyY19jb2ZmZWUvcG9zaXRpb24uY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTtBQUFBLE1BQUE7O0VBQUEsTUFBTSxDQUFDLE9BQVAsR0FDUTtJQUNTLGtCQUFDLENBQUQsRUFBSyxDQUFMO01BQUMsSUFBQyxDQUFBLElBQUQ7TUFBSSxJQUFDLENBQUEsSUFBRDtJQUFMOzt1QkFFYixPQUFBLEdBQVMsU0FBQyxHQUFEO2FBQ1AsSUFBQyxDQUFBLENBQUQsS0FBTSxHQUFHLENBQUMsQ0FBVixJQUFnQixJQUFDLENBQUEsQ0FBRCxLQUFNLEdBQUcsQ0FBQztJQURuQjs7dUJBR1QsSUFBQSxHQUFNLFNBQUMsU0FBRDtNQUNKLElBQUcsU0FBQSxLQUFhLElBQWhCO0FBQ0UsZUFBTyxJQUFJLFFBQUosQ0FBYSxJQUFDLENBQUEsQ0FBZCxFQUFpQixJQUFDLENBQUEsQ0FBRCxHQUFLLENBQXRCLEVBRFQ7T0FBQSxNQUVLLElBQUcsU0FBQSxLQUFhLE1BQWhCO0FBQ0gsZUFBTyxJQUFJLFFBQUosQ0FBYSxJQUFDLENBQUEsQ0FBZCxFQUFpQixJQUFDLENBQUEsQ0FBRCxHQUFLLENBQXRCLEVBREo7T0FBQSxNQUVBLElBQUcsU0FBQSxLQUFhLE1BQWhCO0FBQ0gsZUFBTyxJQUFJLFFBQUosQ0FBYSxJQUFDLENBQUEsQ0FBRCxHQUFLLENBQWxCLEVBQXFCLElBQUMsQ0FBQSxDQUF0QixFQURKO09BQUEsTUFFQSxJQUFHLFNBQUEsS0FBYSxPQUFoQjtBQUNILGVBQU8sSUFBSSxRQUFKLENBQWEsSUFBQyxDQUFBLENBQUQsR0FBSyxDQUFsQixFQUFxQixJQUFDLENBQUEsQ0FBdEIsRUFESjtPQUFBLE1BQUE7QUFHSCxlQUFPLEtBSEo7O0lBUEQ7Ozs7O0FBUFYiLCJzb3VyY2VzQ29udGVudCI6WyJtb2R1bGUuZXhwb3J0cyA9XG4gIGNsYXNzIFBvc2l0aW9uXG4gICAgY29uc3RydWN0b3I6IChAaSwgQGopIC0+XG5cbiAgICBpc0VxdWFsOiAocG9zKSAtPlxuICAgICAgQGkgaXMgcG9zLmkgYW5kIEBqIGlzIHBvcy5qXG5cbiAgICBuZXh0OiAoZGlyZWN0aW9uKSAtPlxuICAgICAgaWYgZGlyZWN0aW9uID09IFwidXBcIlxuICAgICAgICByZXR1cm4gbmV3IFBvc2l0aW9uKEBpLCBAaiAtIDEpXG4gICAgICBlbHNlIGlmIGRpcmVjdGlvbiA9PSBcImRvd25cIlxuICAgICAgICByZXR1cm4gbmV3IFBvc2l0aW9uKEBpLCBAaiArIDEpXG4gICAgICBlbHNlIGlmIGRpcmVjdGlvbiA9PSBcImxlZnRcIlxuICAgICAgICByZXR1cm4gbmV3IFBvc2l0aW9uKEBpIC0gMSwgQGopXG4gICAgICBlbHNlIGlmIGRpcmVjdGlvbiA9PSBcInJpZ2h0XCJcbiAgICAgICAgcmV0dXJuIG5ldyBQb3NpdGlvbihAaSArIDEsIEBqKVxuICAgICAgZWxzZVxuICAgICAgICByZXR1cm4gbnVsbFxuIl19
//# sourceURL=/Users/gvieira/Dropbox/design/Projects/Hare/hare.io/Framer/Project/src_coffee/position.coffee