// Generated by CoffeeScript 1.12.7
(function() {
  exports.puts = function(obj) {
    return console.log('[*]', obj);
  };

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHJpbnRlci5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsic3JjX2NvZmZlZS9wcmludGVyLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7RUFBQSxPQUFPLENBQUMsSUFBUixHQUFlLFNBQUMsR0FBRDtXQUNiLE9BQU8sQ0FBQyxHQUFSLENBQVksS0FBWixFQUFtQixHQUFuQjtFQURhO0FBQWYiLCJzb3VyY2VzQ29udGVudCI6WyJleHBvcnRzLnB1dHMgPSAob2JqKSAtPlxuICBjb25zb2xlLmxvZygnWypdJywgb2JqKVxuIl19
//# sourceURL=/Users/gvieira/Dropbox/design/Projects/Hare/hare.io/Framer/Project/src_coffee/printer.coffee