// Generated by CoffeeScript 1.12.7
(function() {
  var __, chai, hare, lg, test_results, tests;

  __ = require('./utils');

  chai = require('chai');

  hare = require('./hare');

  lg = console.log;

  test_results = [];

  tests = {
    hare: {
      tokenize: {
        '(1 2 3)': ['[', '1', '2', '3', ']']
      }
    }
  };

  _.each(tests, function(test) {
    var error;
    try {
      chai.expect(test["in"]).to.deep.equal(test.out);
      return console.log("☑ " + test.name);
    } catch (error1) {
      error = error1;
      return console.error("☒ " + test.name);
    }
  });

  module.exports = {
    run: function() {
      lg('Running tests...');
      return lg(tests);
    }
  };

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdHMuanMiLCJzb3VyY2VSb290IjoiLi4iLCJzb3VyY2VzIjpbInNyY19jb2ZmZWUvdGVzdHMuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTtBQUFBLE1BQUE7O0VBQUEsRUFBQSxHQUFLLE9BQUEsQ0FBUSxTQUFSOztFQUNMLElBQUEsR0FBTyxPQUFBLENBQVEsTUFBUjs7RUFDUCxJQUFBLEdBQU8sT0FBQSxDQUFRLFFBQVI7O0VBRVAsRUFBQSxHQUFLLE9BQU8sQ0FBQzs7RUFFYixZQUFBLEdBQWU7O0VBQ2YsS0FBQSxHQUNFO0lBQUEsSUFBQSxFQUNFO01BQUEsUUFBQSxFQUNFO1FBQUEsU0FBQSxFQUFXLENBQUMsR0FBRCxFQUFNLEdBQU4sRUFBVyxHQUFYLEVBQWdCLEdBQWhCLEVBQXFCLEdBQXJCLENBQVg7T0FERjtLQURGOzs7RUFJRixDQUFDLENBQUMsSUFBRixDQUFPLEtBQVAsRUFBYyxTQUFDLElBQUQ7QUFDWixRQUFBO0FBQUE7TUFDRSxJQUFJLENBQUMsTUFBTCxDQUFZLElBQUksRUFBQyxFQUFELEVBQWhCLENBQW9CLENBQUMsRUFBRSxDQUFDLElBQUksQ0FBQyxLQUE3QixDQUFtQyxJQUFJLENBQUMsR0FBeEM7YUFDQSxPQUFPLENBQUMsR0FBUixDQUFZLElBQUEsR0FBSyxJQUFJLENBQUMsSUFBdEIsRUFGRjtLQUFBLGNBQUE7TUFHTTthQUNKLE9BQU8sQ0FBQyxLQUFSLENBQWMsSUFBQSxHQUFLLElBQUksQ0FBQyxJQUF4QixFQUpGOztFQURZLENBQWQ7O0VBT0EsTUFBTSxDQUFDLE9BQVAsR0FDRTtJQUFBLEdBQUEsRUFBSyxTQUFBO01BQ0gsRUFBQSxDQUFHLGtCQUFIO2FBQ0EsRUFBQSxDQUFHLEtBQUg7SUFGRyxDQUFMOztBQXBCRiIsInNvdXJjZXNDb250ZW50IjpbIl9fID0gcmVxdWlyZSAnLi91dGlscydcbmNoYWkgPSByZXF1aXJlKCdjaGFpJylcbmhhcmUgPSByZXF1aXJlKCcuL2hhcmUnKVxuXG5sZyA9IGNvbnNvbGUubG9nXG5cbnRlc3RfcmVzdWx0cyA9IFtdXG50ZXN0cyA9XG4gIGhhcmU6XG4gICAgdG9rZW5pemU6XG4gICAgICAnKDEgMiAzKSc6IFsnWycsICcxJywgJzInLCAnMycsICddJ11cblxuXy5lYWNoIHRlc3RzLCAodGVzdCkgLT5cbiAgdHJ5XG4gICAgY2hhaS5leHBlY3QodGVzdC5pbikudG8uZGVlcC5lcXVhbCh0ZXN0Lm91dClcbiAgICBjb25zb2xlLmxvZyhcIuKYkSAje3Rlc3QubmFtZX1cIilcbiAgY2F0Y2ggZXJyb3JcbiAgICBjb25zb2xlLmVycm9yKFwi4piSICN7dGVzdC5uYW1lfVwiKVxuXG5tb2R1bGUuZXhwb3J0cyA9XG4gIHJ1bjogKCkgLT5cbiAgICBsZygnUnVubmluZyB0ZXN0cy4uLicpXG4gICAgbGcodGVzdHMpXG4iXX0=
//# sourceURL=/Users/gvieira/code/hare/hare_framer/src_coffee/tests.coffee