// Generated by CoffeeScript 1.12.7
(function() {
  var assert, chai, hare, lg;

  assert = require('assert');

  chai = require('chai');

  hare = require('./hare');

  lg = console.log;

  describe('hare', function() {
    return describe('#tokenize()', function() {
      var output;
      output = hare.tokenize('(1 2 3)');
      return assert.equal(output, ['[', '1', '2', '3', ']']);
    });
  });

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdF9oYXJlLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJzcmNfY29mZmVlL3Rlc3RfaGFyZS5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUVBO0FBQUEsTUFBQTs7RUFBQSxNQUFBLEdBQVMsT0FBQSxDQUFRLFFBQVI7O0VBQ1QsSUFBQSxHQUFPLE9BQUEsQ0FBUSxNQUFSOztFQUNQLElBQUEsR0FBTyxPQUFBLENBQVEsUUFBUjs7RUFHUCxFQUFBLEdBQUssT0FBTyxDQUFDOztFQUdiLFFBQUEsQ0FBUyxNQUFULEVBQWlCLFNBQUE7V0FDZixRQUFBLENBQVMsYUFBVCxFQUF3QixTQUFBO0FBQ3RCLFVBQUE7TUFBQSxNQUFBLEdBQVMsSUFBSSxDQUFDLFFBQUwsQ0FBYyxTQUFkO2FBQ1QsTUFBTSxDQUFDLEtBQVAsQ0FBYSxNQUFiLEVBQXFCLENBQUMsR0FBRCxFQUFNLEdBQU4sRUFBVyxHQUFYLEVBQWdCLEdBQWhCLEVBQXFCLEdBQXJCLENBQXJCO0lBRnNCLENBQXhCO0VBRGUsQ0FBakI7QUFSQSIsInNvdXJjZXNDb250ZW50IjpbIiMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjXG4jIGltcG9ydHNcbmFzc2VydCA9IHJlcXVpcmUgJ2Fzc2VydCdcbmNoYWkgPSByZXF1aXJlKCdjaGFpJylcbmhhcmUgPSByZXF1aXJlKCcuL2hhcmUnKVxuIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyNcbiMgYWxpYXNcbmxnID0gY29uc29sZS5sb2dcbiMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjXG4jIHRlc3RzXG5kZXNjcmliZSAnaGFyZScsIC0+XG4gIGRlc2NyaWJlICcjdG9rZW5pemUoKScsIC0+XG4gICAgb3V0cHV0ID0gaGFyZS50b2tlbml6ZSAnKDEgMiAzKSdcbiAgICBhc3NlcnQuZXF1YWwgb3V0cHV0LCBbJ1snLCAnMScsICcyJywgJzMnLCAnXSddXG4iXX0=
//# sourceURL=/Users/gvieira/code/hare/hare_framer/src_coffee/test_hare.coffee